### ISSUE TITLE
Need help with the installation of iio

### ISSUE THREAD

**Issue by anchen507** [cmla/mf2f#1]
He, Dewil! I’m very interested in your great work! But when I try to run this code, I get into troubles. It reports an error “**module iio has no attribute ‘read’** ”. I have installed the **pylibiio (V0.21)**. anything wrong with my installed library?

**Comment by gfacciol** [comment]
Hi, you installed the wrong library, it's:   https://pypi.org/project/iio/

**Comment by anchen507** [comment]
Oh! I got it. Thanks a lot!

**Comment by anchen507** [comment]
Oh! No! I meet some **new problems** when I Install the [**imscript**()](https://github.com/mnhrdt/imscript) :
"
......
src/iio.o: In functioncc  -o bin/cdeint src/misc/cdeint.o src/iio.o src/fancy_image.o -ljpeg -ltiff -lpng -lz -lfftw3f -lm  -lgsl -lgslcblas
 `read_whole_hdf5':
iio.c:(.text+0xfccf): **undefined reference to `H5check_version'**
iio.c:(.text+0xfcdf): **undefined reference to `H5Fopen'**
iio.c:(.text+0xfd7f): undefined cc  -o bin/cgi src/misc/cgi.o src/iio.o src/fancy_image.o -ljpeg -ltiff -lpng -lz -lfftw3f -lm  -lgsl -lgslcblas
reference to `H5Ovisit1'
iio.c:(.text+0xfe09): undefined reference to `H5Dget_type'
iio.c:(.text+0xfe18): undefined reference to `H5Tget_class'
......
iio.c:(.text+0x10143): undefined reference to `H5Dread'
iio.c:(.text+0x101a4): undefined reference to `H5Dclose'
iio.c:(.text+0x101af): undefined reference to `H5Fclose'
iio.c:(.text+0x101b7): undefined reference to `H5garbage_collect'
iio.c:(.text+0x1050c): undefined reference to `H5Dopen2'
src/iio.o: In function `my_hd5open':
iio.c:(.text+0x123db): undefined reference to `H5Ovisit1'
iio.c:(.text+0x12476): undefined reference to `H5Dopen2'
cc  -o bin/cldmask src/misc/cldmask.o src/iio.o src/fancy_image.o -ljpeg -ltiff -lpng -lz -lfftw3f -lm  -lgsl -lgslcblas
**collect2: error: ld returned 1 exit status**
......."

**It seems to lack an HDF5 library. Therefore, I added the library “-llhdf5_serial” in the makefile. However, It still report problems:**
"
iio.c:(.text+0xfd7f): **undefined reference to `H5Ovisit1'**
src/iio.o: In function `my_hd5open':
iio.c:(.text+0x123db): undefined reference to `H5Ovisit1'
collect2: error: ld returned 1 exit status
Makefile:19: recipe for target 'bin/backflow' failed
make: *** [bin/backflow] Error 1
make: *** Waiting for unfinished jobs....
......."
I reinstalled the HD5F library and tried many other approaches, but it doesn’t work. **I don’t know how to solve it. Can you give me some suggestions?**

**Comment by kidanger** [comment]
Instead of modifying the Makefile, I suggest to modify the file `src/iio.c` and comment the following line:
```c
#define I_CAN_HAS_LIBHDF5
```
to
```c
//#define I_CAN_HAS_LIBHDF5
```

**Comment by anchen507** [comment]
Oh! Thanks!!!!! It is working!

**Comment by anchen507** [comment]
> Instead of modifying the Makefile, I suggest to modify the file `src/iio.c` and comment the following line:
> 
> ```c
> #define I_CAN_HAS_LIBHDF5
> ```
> 
> to
> 
> ```c
> //#define I_CAN_HAS_LIBHDF5
> ```
Oh! Thanks!!!!! It is working!

**Comment by pankajsharma47** [comment]
Hello sir, I am new to all these things and wanted to learn this but the run.sh file is giving an error. Can you please help me regarding this. Is it necessary for input to be .tiff format?

run.sh: line 18: [: C:\Users\Pankaj: binary operator expected
run.sh: line 21: [: C:\Users\Pankaj: binary operator expected
run.sh: line 24: [: C:\Users\Pankaj: binary operator expected
run.sh: line 27: [: C:\Users\Pankaj: binary operator expected
run.sh: line 30: [: C:\Users\Pankaj: binary operator expected
run.sh: line 33: [: C:\Users\Pankaj: binary operator expected
run.sh: line 36: [: C:\Users\Pankaj: binary operator expected
run.sh: line 39: [: C:\Users\Pankaj: binary operator expected
run.sh: line 42: [: C:\Users\Pankaj: binary operator expected
tvl1flow.sh: line 15: parallel: command not found
seq: invalid floating point argument: ‘Sharma\\Desktop\\mf2f-master\\test\\noise.MOV’
Try 'seq --help' for more information.
flows computed
compute_mask.sh: line 12: parallel: command not found
seq: invalid floating point argument: ‘Sharma\\Desktop\\mf2f-master/flow/%03d.flo’
Try 'seq --help' for more information.
collision masks computed
run.sh: line 75: python3.6: command not found
rm: cannot remove 'C:\Users\Pankaj': No such file or directory
rm: cannot remove 'Sharma\Desktop\mf2f-master/downs.tiff': No such file or directory
rm: cannot remove 'C:\Users\Pankaj': No such file or directory
rm: cannot remove 'Sharma\Desktop\mf2f-master/downs_warp.tiff': No such file or directory
rm: cannot remove 'C:\Users\Pankaj': No such file or directory
rm: cannot remove 'Sharma\Desktop\mf2f-master/dwo.png': No such file or directory
rm: cannot remove 'C:\Users\Pankaj': No such file or directory
rm: cannot remove 'Sharma\Desktop\mf2f-master/mask_invalid_pixels.png': No such file or directory
rm: cannot remove 'C:\Users\Pankaj': No such file or directory
rm: cannot remove 'Sharma\Desktop\mf2f-master/warping_error.tiff': No such file or directory
rm: cannot remove 'C:\Users\Pankaj': No such file or directory
rm: cannot remove 'Sharma\Desktop\mf2f-master/warp.tiff': No such file or directory
rm: cannot remove 'C:\Users\Pankaj': No such file or directory
rm: cannot remove 'Sharma\Desktop\mf2f-master/WERR.tiff': No such file or directory
warping res masks computed
run.sh: line 83: python3.6: command not found
FastDVDnet-8sigmas computed
run.sh: line 87: python3.6: command not found
online no teacher computed
run.sh: line 92: python3.6: command not found
online with teacher computed
run.sh: line 97: python3.6: command not found
offline no teacher computed
run.sh: line 102: python3.6: command not found
